/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-06-14 05:23:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.user.User;
import models.user.Order;
import dao.OrderDAO;
import java.util.List;
import java.text.SimpleDateFormat;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("models.user.Order");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("models.user.User");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("dao.OrderDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User currentUser = (User) session.getAttribute("user");
    String displayName = "Guest";
    int userId = 0;

    if (currentUser != null) {
        displayName = currentUser.getUsername();
        userId = currentUser.getId();
    } else {
        // Redirect to login if not logged in
        response.sendRedirect(request.getContextPath() + "/auth/login");
        return;
    }

    // Get user's order history
    OrderDAO orderDAO = new OrderDAO();
    List<Order> userOrders = orderDAO.getOrdersByUserId(userId);
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMM yyyy");

    // Get count of user's orders
    int totalOrders = userOrders != null ? userOrders.size() : 0;

    // Calculate total spending if orders exist
    double totalSpending = 0;
    if (userOrders != null) {
        for (Order order : userOrders) {
            totalSpending += order.getProductPrice();
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Riwayat Pembelian - Thrifting Store</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../styles/components/user-sidebar.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../styles/dashboard-admin.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .action-buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 16px;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .action-button {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-button {\r\n");
      out.write("            background-color: #ffebee;\r\n");
      out.write("            color: #c62828;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-button:hover {\r\n");
      out.write("            background-color: #ffcdd2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-button {\r\n");
      out.write("            background-color: #e3f2fd;\r\n");
      out.write("            color: #1976d2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-button:hover {\r\n");
      out.write("            background-color: #bbdefb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .home-button {\r\n");
      out.write("            background-color: #e8f5e9;\r\n");
      out.write("            color: #2e7d32;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .home-button:hover {\r\n");
      out.write("            background-color: #c8e6c9;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .action-button svg {\r\n");
      out.write("            margin-right: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header-actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 16px;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-menunggu-konfirmasi {\r\n");
      out.write("            background-color: #feecdc;\r\n");
      out.write("            color: #ff5a1f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-dikonfirmasi {\r\n");
      out.write("            background-color: #e1effe;\r\n");
      out.write("            color: #3f83f8;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-diproses {\r\n");
      out.write("            background-color: #fdf6b2;\r\n");
      out.write("            color: #c27803;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-dikirim {\r\n");
      out.write("            background-color: #def7ec;\r\n");
      out.write("            color: #0e9f6e;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-selesai {\r\n");
      out.write("            background-color: #d1fae5;\r\n");
      out.write("            color: #047857;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-dibatalkan {\r\n");
      out.write("            background-color: #fee2e2;\r\n");
      out.write("            color: #e02424;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-stats-card {\r\n");
      out.write("            background: linear-gradient(135deg, #4a6cf7 0%, #2d3a94 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-stats-card::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            right: -50%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 200%;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            transform: rotate(30deg);\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-stats-card .stat-info h3,\r\n");
      out.write("        .user-stats-card .stat-value {\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-stats-card .stat-icon {\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-text-highlight {\r\n");
      out.write("            color: #4a6cf7;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-title-bar {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-title-bar h2 {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding-left: 15px;\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-title-bar h2:before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 5px;\r\n");
      out.write("            background-color: #4a6cf7;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../components/user-sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-content\">\r\n");
      out.write("    <div class=\"welcome-header\">\r\n");
      out.write("        <h1>Riwayat Pembelian <span class=\"welcome-text-highlight\">");
      out.print( displayName );
      out.write("</span></h1>\r\n");
      out.write("        <p>Berikut adalah ringkasan aktivitas belanja anda di Thrifting Store</p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"action-buttons\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"action-button home-button\">\r\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                    <path d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"></path>\r\n");
      out.write("                    <polyline points=\"9 22 9 12 15 12 15 22\"></polyline>\r\n");
      out.write("                </svg>\r\n");
      out.write("                Homepage\r\n");
      out.write("            </a>\r\n");
      out.write("            ");
 if (currentUser != null) { 
      out.write("\r\n");
      out.write("                <form action=\"");
      out.print( request.getContextPath() );
      out.write("/auth/logout\" method=\"GET\">\r\n");
      out.write("                    <button class=\"action-button logout-button\" type=\"submit\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                            <path d=\"M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4\"></path>\r\n");
      out.write("                            <polyline points=\"16 17 21 12 16 7\"></polyline>\r\n");
      out.write("                            <line x1=\"21\" y1=\"12\" x2=\"9\" y2=\"12\"></line>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                        Logout\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/auth/login\" class=\"action-button login-button\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                        <path d=\"M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4\"></path>\r\n");
      out.write("                        <polyline points=\"10 17 15 12 10 7\"></polyline>\r\n");
      out.write("                        <line x1=\"15\" y1=\"12\" x2=\"3\" y2=\"12\"></line>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    Login\r\n");
      out.write("                </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"dashboard-stats\">\r\n");
      out.write("        <div class=\"stat-card user-stats-card\">\r\n");
      out.write("            <div class=\"stat-icon\">\r\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                    <path d=\"M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z\"></path>\r\n");
      out.write("                    <line x1=\"3\" y1=\"6\" x2=\"21\" y2=\"6\"></line>\r\n");
      out.write("                    <path d=\"M16 10a4 4 0 0 1-8 0\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-info\">\r\n");
      out.write("                <h3>Total Pesanan</h3>\r\n");
      out.write("                <p class=\"stat-value\">");
      out.print( totalOrders );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-card user-stats-card\">\r\n");
      out.write("            <div class=\"stat-icon\">\r\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                    <line x1=\"12\" y1=\"1\" x2=\"12\" y2=\"23\"></line>\r\n");
      out.write("                    <path d=\"M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-info\">\r\n");
      out.write("                <h3>Total Belanja</h3>\r\n");
      out.write("                <p class=\"stat-value\">Rp ");
      out.print( String.format("%,.0f", totalSpending) );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"dashboard-sections\">\r\n");
      out.write("        <div class=\"section\">\r\n");
      out.write("            <div class=\"section-title-bar\">\r\n");
      out.write("                <h2>Riwayat Pembelian</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"data-table\">\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>Tanggal</th>\r\n");
      out.write("                            <th>Nama Produk</th>\r\n");
      out.write("                            <th>Harga</th>\r\n");
      out.write("                            <th>Alamat Pengiriman</th>\r\n");
      out.write("                            <th>Status</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");
 if(userOrders != null && !userOrders.isEmpty()) { 
      out.write("\r\n");
      out.write("                            ");
 for(Order order : userOrders) { 
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>");
      out.print( dateFormat.format(order.getCreatedAt()) );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( order.getProductName() );
      out.write("</td>\r\n");
      out.write("                                    <td>Rp ");
      out.print( String.format("%,.0f", order.getProductPrice()) );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( order.getShippingAddress() );
      out.write("</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span class=\"status-badge status-");
      out.print( order.getOrderStatus().toLowerCase().replace(" ", "-") );
      out.write("\">\r\n");
      out.write("                                            ");
      out.print( order.getOrderStatus() );
      out.write("\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"5\">\r\n");
      out.write("                                    <div class=\"no-data\">\r\n");
      out.write("                                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"48\" height=\"48\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#999\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                            <circle cx=\"9\" cy=\"21\" r=\"1\"></circle>\r\n");
      out.write("                                            <circle cx=\"20\" cy=\"21\" r=\"1\"></circle>\r\n");
      out.write("                                            <path d=\"M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <p style=\"margin-top: 15px;\">Anda belum memiliki riwayat pembelian</p>\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"add-btn\" style=\"margin-top: 15px; display: inline-flex;\">\r\n");
      out.write("                                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                                <circle cx=\"9\" cy=\"21\" r=\"1\"></circle>\r\n");
      out.write("                                                <circle cx=\"20\" cy=\"21\" r=\"1\"></circle>\r\n");
      out.write("                                                <path d=\"M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6\"></path>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                            Belanja Sekarang\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
